function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("left") then
		local position = go.get_position("#")
		position.x = position.x - 5
		go.set_position(position, "#")
	elseif action_id == hash("right") then
		local position = go.get_position("#")
		position.x = position.x + 5
		go.set_position(position, "#")
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end