go.property("camera_id", hash("/camera"))
local camera = require "orthographic.camera"


function init(self)
	self.colliding = {}
	self.mouse_pos = vmath.vector3()
	msg.post(".", "acquire_input_focus")
end




function update(self, dt)
	local pos = camera.screen_to_world(self.camera_id, self.mouse_pos)
	pos.z = 99
	go.set_position(pos, "#")
end




function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		if message.enter then
			self.colliding[message.other_id] = true
		else
			self.colliding[message.other_id] = nil
		end
	elseif message_id == hash("get_colliding") then
		local other = next(self.colliding)
		msg.post(sender, "set_target", { id = other })
	end
end




function on_input(self, action_id, action)
	if action.x and action.y then
		self.mouse_pos.x, self.mouse_pos.y = action.x, action.y
	elseif action_id == hash("click") and action.released then
		msg.post(".", "get_colliding")
	end
end



